/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPrevisoesRouteImport } from './routes/_authenticated/previsoes'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedTransacoesRouteImport } from './routes/_authenticated/transacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrevisoesRoute = AuthenticatedPrevisoesRouteImport.update({
  id: '/previsoes',
  path: '/previsoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransacoesRoute = AuthenticatedTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/previsoes': typeof AuthenticatedPrevisoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/transacoes': typeof AuthenticatedTransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/previsoes': typeof AuthenticatedPrevisoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/transacoes': typeof AuthenticatedTransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/previsoes': typeof AuthenticatedPrevisoesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/transacoes': typeof AuthenticatedTransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/categorias'
    | '/dashboard'
    | '/metas'
    | '/orcamentos'
    | '/previsoes'
    | '/relatorios'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/categorias'
    | '/dashboard'
    | '/metas'
    | '/orcamentos'
    | '/previsoes'
    | '/relatorios'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/categorias'
    | '/_authenticated/dashboard'
    | '/_authenticated/metas'
    | '/_authenticated/orcamentos'
    | '/_authenticated/previsoes'
    | '/_authenticated/relatorios'
    | '/_authenticated/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/previsoes': {
      id: '/_authenticated/previsoes'
      path: '/previsoes'
      fullPath: '/previsoes'
      preLoaderRoute: typeof AuthenticatedPrevisoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacoes': {
      id: '/_authenticated/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AuthenticatedTransacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPrevisoesRoute: typeof AuthenticatedPrevisoesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTransacoesRoute: typeof AuthenticatedTransacoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPrevisoesRoute: AuthenticatedPrevisoesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTransacoesRoute: AuthenticatedTransacoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
